### ISSUE TITLE
Plugin feature request: keep original surround track with the1poet surround to ac3 plugin

### ISSUE THREAD

**Issue by jayelg** [HaveAGitGat/Tdarr_Plugins#118]
Loving Tdarr!
Regarding plugin: the1poet Video surround sound to ac3
I would like the ability to keep existing surround sound track along with the transcoded ac3 track (For future-proofing library). from a quick search it appears achievable in a ffmpeg command and I think it would be preferrable to integrate into existing plugin. Thoughts?

**Comment by michpas** [comment]
Hi. Such a feature would indeed be great. I was looking for the same. In addition, this plugin could also benefit from a selector AC3 or EAC3 and a bitrate selection (to max 640k); bit similar to the other plugin 'chang audiostream codec'

Just for sharing, to enable the 'adding' of an audiostream I eventually used the plugin creator and created multiple filters. Eg. if no AC or EAC3 and where dts is available, create new audio track. This plugin creator is language focussed, so it is needed to create multiple plugins to ensure enough coverage. Not ideal but it works.

Using the Poet1 video surround sound is much better as I think it just  'creates a AC3 file for any available 5+ audiofile; for all potential languages that it is offered. So if a file has DTS EN and DTS French; the end result would be AC EN and AC French ; and in out case it would be great if these can indeed be added to the original, in stead of replaced.

Hope this helps in further working a solution

**Comment by michpas** [comment]
Hi Jayelg,
I have been further looking for the best option to solve this situation. Found the included plugin to be reallty good for this purpose. You might want to check it out: Tdarr_Plugin_henk_Add_Specific_Audio_Codec
You can set the source filter to: dts,truehd

**Comment by michpas** [comment]
> Loving Tdarr!
> Regarding plugin: the1poet Video surround sound to ac3
> I would like the ability to keep existing surround sound track along with the transcoded ac3 track (For future-proofing library). from a quick search it appears achievable in a ffmpeg command and I think it would be preferrable to integrate into existing plugin. Thoughts?

Hi Jayelg,
I have been further looking for the best option to solve this situation. Found the included plugin to be reallty good for this purpose. You might want to check it out: Tdarr_Plugin_henk_Add_Specific_Audio_Codec
You can set the source filter to: dts,truehd

**Comment by HaveAGitGat** [comment]
I've added an option so you can select whether to overwriteTracks or not:
![image](https://user-images.githubusercontent.com/43864057/146143922-ad14556c-e4f3-4602-9fde-c2770666f28d.png)

**Comment by xeTaiz** [comment]
I just stumbled upon this, as said plugin DID replace the original tracks despite `overwriteTracks` seemingly being set to false.
I want to note that when you simply drag in the plugin, the "true" default is not displayed and the toggle shows the "off" status. When inspecting the flows underlying json, I can see that the value is simply not set, despite suggesting False. The value is only false when the bool is toggled on and off once, otherwise the `"overwriteTracks": "false"` portion of the `inputsDB` is simply missing.

This may be due to an interface update (looks quite different to me compared to the screenshot above). 

The expected behavior given the "true" default would be to show the toggle set to "true" when initially dragging in this node and having the default state present within the json when the plugin is dragged in, not on "first change" of the attribute

Unfortunately I have no clue how to fix this in a PR, but I want to let you know @HaveAGitGat as I would assume this issue may affect other plugins as well.
